services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: armada-api
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fleet-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - fleet-net

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - fleet-net

  armada-api:
    build:
      context: .
      dockerfile: DockerFile
    container_name: armada-api
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: armada-api

      # RabbitMQ URL
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/

      # MQTT Broker
      MQTT_BROKER_URL: tcp://mosquitto:1883
    depends_on:
      - postgres
      - rabbitmq
      - mosquitto
    ports:
      - "8080:8080"
    networks:
      - fleet-net

volumes:
  postgres-data:

networks:
  fleet-net:
