# Stage 1: Build
FROM golang:1.24 as builder

WORKDIR /app

# Copy go.mod & go.sum
COPY go.mod go.sum ./
RUN go mod download

# Copy seluruh source code
COPY . .

# Build binary
RUN go build -o armada-api ./cmd

# Stage 2: Runtime
FROM gcr.io/distroless/static-debian11

WORKDIR /root

# Copy binary dari builder
COPY --from=builder /app/armada-api .

# Run
ENTRYPOINT ["./armada-api", "server"]
